### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by smaragdus** [belijzajac/BerryPlayer#11]
As the screen-shots look nice I would like to ask several questions about [BerryPlayer](https://github.com/belijzajac/BerryPlayer):

- Which audio formats are supported?
- Does it support playlist formats?
- Does it support cue sheets?
- Is it supposed to run under Windows?
- Are there any compiled binaries for Windows?

Regards

**Comment by belijzajac** [comment]
Hey there,

unfortunately, the project is no longer maintained, because it was made just for practicing the Qt5 library. It lacks the most of things that modern music players have, and there was no intention to make it a fully fledged music player in the first place. You should look into other projects

**Comment by smaragdus** [comment]
@belijzajac 

Thanks for the quick response and for the detailed information you provided.

In am closing this issue then.

If it happens that you change your mind in the future and choose to develop this project further I may have another look.

Good luck.
